### ISSUE TITLE
Calibrate system by touching Bregma and Lambda

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#121]
Suggested from lab meeting: have user touch Bregma and touch Lambda and use these two points in needle space to calibrate the probe positions in the planner

**Comment by dbirman** [comment]
Closing this since we have this solved. Small comment -- maybe we should use the name "zero coordinate" (so in settings it would read "reset zero coordinate" instead of "reset bregma") instead of explicitly calling it Bregma. This way someone who wants their zero coordinate to be lambda or some other point can do that.
