### ISSUE TITLE
Start interfacing with server

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#80]
- [x] Implement BestHTTP to connect to server (place in empty)
- [x] Get position from irl and bring that into Unity
- [x] `TP_ ProbeController.cs`: Add function to put the irl position into Unity (use `ManualCoordinateEntry`)

**Comment by dbirman** [comment]
Just added some code documentation and I need to write down some notes about the Unity side of the sensapex link. There's a lot going on here, so probably several points where we'll want to discuss together before anything gets implemented. 

First you'll need to add some kind of manager component, `SensapexManager` or something which can talk to your websocket server and pull/push data. Once that's working you can modify the UI to add a dropdown menu for each probe that lets you select which manipulator the probe is linked to. When the probe is linked it should set a flag in the `TP_ProbeController` component attached to the probe which prevents the user from inputting movements themselves.

Right now `TP_ProbeController` has two ways of getting inputs to move a probe, either calling MoveProbe() which checks for keyboard input and is called by the Update() function in TrajectoryPlanagerManager or by calling DragMovementDrag() which is called by the `TP_ProbeCollider` component attached to the collidable parts of the probe gameobject when they are clicked on.

With those disabled you can use the Update() function in ProbeController to poll the sensapex manager and then use SetProbePosition() to position the probe itself. Setting the probe position has two steps: (1) you have to set the coordinate in CCF space. (2) you have to set the angles. You'll have to sort out how x/y/z convert to ap/ml/dv in ccf space, and you'll have to query the user to tell you what the angles of the probe are since there's no way to get that information from the manipulator. Phi is the rotation of the manipulator, theta is the angle of the front arm, and spin is only used if the probe is upside-down or sideways for some reason. 

Two extra levels of complications. Level 1 is that for the coordinates you get are relative to Bregma. To go back to CCF space you need to add iblBregma to the manipulator coordinates. For example, if the manipulator is at (ap=0, ml=0, dv=0) relative to bregma you are actually at (+5.4, +5.7, +0.33) in CCF space. It can be helpful to look at the CCF space box to understand what's going on, which you can turn on by enabling the ccfSpaceBox gameobject in BrainParts>BrainModel>root>ccfSpaceBox. If you turn the skull rig on you can also see bregma, it's the point where the skull plates come together sort of in the middle/front of the skull. The back point where the sutures join is called lambda.

Level 2 of the complication is that actually when you're in the real mouse brain you aren't in CCF space at all you're in "in vivo" coordinates which are some unknown transformation from CCF space. You'll see that there are some locations in ProbeController (and other parts of the codebase) where I use CoordinateTransform objects by calling the function `CoordinateTransformToCCF` or `CoordinateTransformFromCCF` in `TP_TrajectoryPlannerManager` -- this is because CCF space was built using the brain of a fixed mouse (i.e. not in the mouse's skull anymore), because of the fixing process + without the pressure of being in the skull the CCF space ended up being deformed from the real in vivo mouse brain. We have some good estimates of this deformation, so it's possible to switch coordinates in CCF space to "in vivo" transformed space (which we're calling the NeedlesTransform for now, eventually we will have other transforms) and back. Most users want to be in NeedlesTransform space, not CCF space, but because we want to be able to support multiple different transforms (e.g. if a user *knows* the transform for their mouse, they should be able to upload it as a file) we have to be prepared to swap these out. So the coordinates from the manipulator are not only bregma-relative they are actually in the transformed space and need to be converted back to CCF by calling the `CoordinateTransformToCCF` function.

Whew, big note, we can discuss details in future weeks.

**Comment by dbirman** [comment]
Some more notes to myself so I don't forget:
- x/y/z should translate directly to ap/ml/dv on each axis in the Insertion class as long as you as a CoordinateTransform
- Bregma is now built-in to the CoordinateTransform so no need to account for it in an extra step (at least for Needles, but we should really use MRI-Linear)
- Probably need to add depth back into the planner to be able to handle linking, since at the link moment the probe is at a negative depth position?
